version: "3.9"
services:
  backend:
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  frontend:
    build: .
    command: streamlit run ui.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
