[general]
email = "your-email@example.com"

[server]
headless = true
port = 8501

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#1a365d"
font = "sans serif"
